name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create a volume for report sharing
        run: docker volume create bookstore-report-vol

      - name: Build Docker Image
        run: docker build -t bookstore-api-tests .

      - name: Run Tests inside Container with Volume Mount
        run: |
          set +e
          docker run --rm \
            -v bookstore-report-vol:/app/test-output \
            bookstore-api-tests
          exit 0

      - name: Copy ExtentReport.html from volume
        run: |
          docker run --rm \
            -v bookstore-report-vol:/data \
            -v ${{ github.workspace }}:/output \
            alpine cp /data/ExtentReport.html /output/ExtentReport.html

      - name: Upload ExtentReport for download
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: ./ExtentReport.html

      - name: Upload report to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./ExtentReport.html
          name: github-pages

  publish-report:
    name: Publish Extent Report to GitHub Pages
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4

      - name: Add link to summary
        run: |
          echo "### [View Extent Report](${{ steps.deploy.outputs.page_url }})" >> $GITHUB_STEP_SUMMARY
