name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Docker Image and Run Tests
        run: |
          docker build -t bookstore-api-tests .

      - name: Create container and copy ExtentReport.html
        run: |
          container_id=$(docker create bookstore-api-tests)
          docker cp "$container_id:/app/test-output/ExtentReport.html" ./ExtentReport.html
          docker rm "$container_id"

      - name: Upload ExtentReport as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExtentReport
          path: ./ExtentReport.html
